#!/bin/bash
docker run -it --rm \
    --name filezilla \
    --user=$USER \
    --env="DISPLAY" \
    --workdir="/home/$USER" \
    --volume="/home/$USER:/home/$USER" \
    --volume="/etc/group:/etc/group:ro" \
    --volume="/etc/passwd:/etc/passwd:ro" \
    --volume="/etc/shadow:/etc/shadow:ro" \
    --volume="/etc/sudoers.d:/etc/sudoers.d:ro" \
    -v /etc/machine-id:/etc-machine-id:ro \
    --volume="/tmp/.X11-unix:/tmp/.X11-unix:rw" \
    -v /etc/localtime:/etc/localtime:ro \
    --hostname docker-filezilla \
tsari/filezilla