#!/bin/bash
user=$USER
uid=$(id -u)
gid=$(id -g)
sudo docker run -it --rm \
    -e "USER=$user" \
    -e "UID=$uid" \
    -e "GID=$gid" \
    -e "HOME=/home/$user" \
    -v /home/$user:/home/$user \
    -v /etc/machine-id:/etc-machine-id:ro \
    -v /etc/localtime:/etc/localtime:ro \
    -v $PWD:/app \
tsari/build-server node "$@"